In [1]:
import numpy as np
import tensorflow as tf

In [2]:
x = np.arange(20).reshape(10, -1)

In [3]:
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [4]:
theta = 10*np.arange(20).reshape(10, -1)

In [5]:
y0 = np.zeros(x.shape[0]).reshape(10, -1)
y1 = np.ones(x.shape[0]).reshape(10, -1)

In [6]:
dy0 = tf.data.Dataset.from_tensor_slices(y0)
dy1 = tf.data.Dataset.from_tensor_slices(y1)

In [7]:
dx = tf.data.Dataset.from_tensor_slices(x)
dtheta = tf.data.Dataset.from_tensor_slices(theta)

In [8]:
d = tf.data.Dataset.zip((dx, dtheta))

In [9]:
d.element_spec.dtype

AttributeError: 'tuple' object has no attribute 'dtype'

In [10]:
g = tf.data.Dataset.from_generator(dx.batch(3).__iter__, output_types=dx.element_spec.dtype)

In [11]:
for h in tf.data.Dataset.from_tensor_slices([dx, dx.shuffle(5)]).interleave(lambda x : x):
    print(h)

Cause: could not parse the source code:

for h in tf.data.Dataset.from_tensor_slices([dx, dx.shuffle(5)]).interleave(lambda x : x):

This error may be avoided by creating the lambda in a standalone statement.

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Cause: could not parse the source code:

for h in tf.data.Dataset.from_tensor_slices([dx, dx.shuffle(5)]).interleave(lambda x : x):

This error may be avoided by creating the lambda in a standalone statement.

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
tf.Tensor([0 1], shape=(2,), dtype=int64)
tf.Tensor([2 3], shape=(2,), dtype=int64)
tf.Tensor([2 3], shape=(2,), dtype=int64)
tf.Tensor([0 1], shape=(2,), dtype=int64)
tf.Tensor([4 5], shape=(2,), dtype=int64)
tf.Tensor([6 7], shape=(2,), dtype=int64)
tf.Tensor([6 7], shape=(2,), dtype=int64)
tf.Tensor([4 5], shape=(2,), dtype=int64)
tf.Tensor([8 9], shape=(2,), dtype=int64)
tf.Tensor([8 9

In [12]:
for h in tf.data.Dataset.from_tensor_slices([dy1, dy0]).interleave(lambda x : x):
    print(h)

Cause: could not parse the source code:

for h in tf.data.Dataset.from_tensor_slices([dy1, dy0]).interleave(lambda x : x):

This error may be avoided by creating the lambda in a standalone statement.

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Cause: could not parse the source code:

for h in tf.data.Dataset.from_tensor_slices([dy1, dy0]).interleave(lambda x : x):

This error may be avoided by creating the lambda in a standalone statement.

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
tf.Tensor([1.], shape=(1,), dtype=float64)
tf.Tensor([0.], shape=(1,), dtype=float64)
tf.Tensor([1.], shape=(1,), dtype=float64)
tf.Tensor([0.], shape=(1,), dtype=float64)
tf.Tensor([1.], shape=(1,), dtype=float64)
tf.Tensor([0.], shape=(1,), dtype=float64)
tf.Tensor([1.], shape=(1,), dtype=float64)
tf.Tensor([0.], shape=(1,), dtype=float64)
tf.Tensor([1.], shape=(1,), dtype=float64)
tf.Tensor([0.], shape=(

In [13]:
xs = tf.data.Dataset.from_tensor_slices([dx, dx]).interleave(lambda x : x)
ts = tf.data.Dataset.from_tensor_slices([dx, dtheta.shuffle(5)]).interleave(lambda x : x)
ys = tf.data.Dataset.from_tensor_slices([dy1, dy0]).interleave(lambda x : x)

In [52]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:XLA_CPU:0', device_type='XLA_CPU'),
 PhysicalDevice(name='/physical_device:XLA_GPU:0', device_type='XLA_GPU'),
 PhysicalDevice(name='/physical_device:XLA_GPU:1', device_type='XLA_GPU'),
 PhysicalDevice(name='/physical_device:XLA_GPU:2', device_type='XLA_GPU'),
 PhysicalDevice(name='/physical_device:XLA_GPU:3', device_type='XLA_GPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'),
 PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU'),
 PhysicalDevice(name='/physical_device:GPU:2', device_type='GPU'),
 PhysicalDevice(name='/physical_device:GPU:3', device_type='GPU')]

In [44]:
from tensorflow.python.framework import device_spec

In [57]:
device_spec.DeviceSpecV2().from_string('GPU:0')

In [41]:
':'.join(tf.config.list_physical_devices(device_type="GPU")[0].name.split(':')[1:])

'GPU:0'

In [14]:
data = tf.data.Dataset.zip((tf.data.Dataset.zip((xs, ts)), ys))

In [43]:
data.batch(5).apply(tf.data.experimental.prefetch_to_device(tf.config.list_physical_devices(device_type="GPU")[0].name))

ValueError: Unknown attribute: 'physical_device' in '/physical_device:GPU:0'

In [18]:


data.batch(4).prefetch_t_device()

AttributeError: 'BatchDataset' object has no attribute 'prefetch_t_device'

In [16]:
list(xs.as_numpy_iterator())

[array([0, 1]),
 array([0, 1]),
 array([2, 3]),
 array([2, 3]),
 array([4, 5]),
 array([4, 5]),
 array([6, 7]),
 array([6, 7]),
 array([8, 9]),
 array([8, 9]),
 array([10, 11]),
 array([10, 11]),
 array([12, 13]),
 array([12, 13]),
 array([14, 15]),
 array([14, 15]),
 array([16, 17]),
 array([16, 17]),
 array([18, 19]),
 array([18, 19])]

In [85]:
next(d.batch(3).__iter__())

(<tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[0, 1],
        [2, 3],
        [4, 5]])>, <tf.Tensor: shape=(3, 2), dtype=int64, numpy=
 array([[ 0, 10],
        [20, 30],
        [40, 50]])>)

In [81]:
d.window(3).batch(3)

<BatchDataset shapes: (DatasetSpec(TensorSpec(shape=(2,), dtype=tf.int64, name=None), TensorShape([None])), DatasetSpec(TensorSpec(shape=(2,), dtype=tf.int64, name=None), TensorShape([None]))), types: (DatasetSpec(TensorSpec(shape=(2,), dtype=tf.int64, name=None), TensorShape([None])), DatasetSpec(TensorSpec(shape=(2,), dtype=tf.int64, name=None), TensorShape([None])))>

In [47]:
for b in d.batch(3).flat_map(lambda x, y: tf.data.Dataset.zip( (tf.data.Dataset.from_tensor_slices(x), tf.data.Dataset.from_tensor_slices(y).shuffle(2) ) )):
    print(b)

Cause: could not parse the source code:

for b in d.batch(3).flat_map(lambda x, y: tf.data.Dataset.zip( (tf.data.Dataset.from_tensor_slices(x), tf.data.Dataset.from_tensor_slices(y).shuffle(2) ) )):

This error may be avoided by creating the lambda in a standalone statement.

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Cause: could not parse the source code:

for b in d.batch(3).flat_map(lambda x, y: tf.data.Dataset.zip( (tf.data.Dataset.from_tensor_slices(x), tf.data.Dataset.from_tensor_slices(y).shuffle(2) ) )):

This error may be avoided by creating the lambda in a standalone statement.

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
(<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 1])>, <tf.Tensor: shape=(2,), dtype=int64, numpy=array([20, 30])>)
(<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 3])>, <tf.Tensor: shape=(2,), dtype=int64, numpy=array([ 0, 10])>)
(<tf.Tensor: sha

In [54]:
for k in tf.data.Dataset.interleave(2, d.batch):
    print(k)

AttributeError: 'int' object has no attribute 'element_spec'

In [173]:
for d in dx.window(5).prefetch(1):
    print(d.shuffle(5))

<ShuffleDataset shapes: (2,), types: tf.int64>
<ShuffleDataset shapes: (2,), types: tf.int64>


In [59]:
r = tf.data.Dataset.range(10)

In [64]:
r.interleave(lambda x : tf.data.Dataset.from_tensors(x))

<InterleaveDataset shapes: (), types: tf.int64>

In [66]:
for l in r.interleave(lambda x : tf.data.Dataset.from_tensors(x)):
    print(l)

tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(6, shape=(), dtype=int64)
tf.Tensor(7, shape=(), dtype=int64)
tf.Tensor(8, shape=(), dtype=int64)
tf.Tensor(9, shape=(), dtype=int64)


In [202]:
list(dx.window(3).map(lambda x: x.shuffle(5)).as_numpy_iterator())

TypeError: Dataset.as_numpy_iterator() does not support datasets containing <class 'tensorflow.python.data.ops.dataset_ops._VariantDataset'>

In [57]:
b.element_spec.dtype

tf.int64

In [ ]:
tf.data.Dataset.window(

In [156]:
b.window(2)

<WindowDataset shapes: DatasetSpec(TensorSpec(shape=(None, 2), dtype=tf.int64, name=None), TensorShape([])), types: DatasetSpec(TensorSpec(shape=(None, 2), dtype=tf.int64, name=None), TensorShape([]))>

In [166]:
for d in dx.window(3):
    print(list(d.shuffle(3).as_numpy_iterator()))

[array([2, 3]), array([0, 1]), array([4, 5])]
[array([8, 9]), array([6, 7]), array([10, 11])]
[array([12, 13]), array([16, 17]), array([14, 15])]
[array([18, 19])]


In [158]:
for d in dx.batch(3):
    print(d.as_numpy_iterator())

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'as_numpy_iterator'

In [10]:
for d in tf.data.Dataset.zip((dx, dtheta.shuffle(10))).shuffle(10):
    print(d)

(<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 1])>, <tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 3])>)
(<tf.Tensor: shape=(2,), dtype=int64, numpy=array([18, 19])>, <tf.Tensor: shape=(2,), dtype=int64, numpy=array([18, 19])>)
(<tf.Tensor: shape=(2,), dtype=int64, numpy=array([4, 5])>, <tf.Tensor: shape=(2,), dtype=int64, numpy=array([10, 11])>)
(<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 3])>, <tf.Tensor: shape=(2,), dtype=int64, numpy=array([8, 9])>)
(<tf.Tensor: shape=(2,), dtype=int64, numpy=array([16, 17])>, <tf.Tensor: shape=(2,), dtype=int64, numpy=array([4, 5])>)
(<tf.Tensor: shape=(2,), dtype=int64, numpy=array([14, 15])>, <tf.Tensor: shape=(2,), dtype=int64, numpy=array([16, 17])>)
(<tf.Tensor: shape=(2,), dtype=int64, numpy=array([12, 13])>, <tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 1])>)
(<tf.Tensor: shape=(2,), dtype=int64, numpy=array([8, 9])>, <tf.Tensor: shape=(2,), dtype=int64, numpy=array([6, 7])>)
(<tf.Tensor: shape=(2,), dtype=int

In [11]:
X = tf.data.Dataset.concatenate(dx, dx)
T = tf.data.Dataset.concatenate(dtheta, dtheta.shuffle(10))
Y = tf.data.Dataset.concatenate(dy1, dy0)

In [12]:
bigD = tf.data.Dataset.zip((X, T, Y))

In [13]:
for x, t, y in bigD.shuffle(20):
    print(x.numpy(), t.numpy(), y.numpy())

[8 9] [14 15] [0.]
[2 3] [18 19] [0.]
[2 3] [2 3] [1.]
[14 15] [6 7] [0.]
[16 17] [2 3] [0.]
[8 9] [8 9] [1.]
[10 11] [10 11] [1.]
[4 5] [0 1] [0.]
[0 1] [0 1] [1.]
[4 5] [4 5] [1.]
[14 15] [14 15] [1.]
[16 17] [16 17] [1.]
[18 19] [12 13] [0.]
[6 7] [4 5] [0.]
[10 11] [10 11] [0.]
[6 7] [6 7] [1.]
[12 13] [12 13] [1.]
[12 13] [16 17] [0.]
[18 19] [18 19] [1.]
[0 1] [8 9] [0.]


In [14]:
s = bigD.shuffle(20)

In [15]:
s

<ShuffleDataset shapes: ((2,), (2,), (1,)), types: (tf.int64, tf.int64, tf.float64)>

In [16]:
for e in s:
    print(e)

(<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 1])>, <tf.Tensor: shape=(2,), dtype=int64, numpy=array([18, 19])>, <tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.])>)
(<tf.Tensor: shape=(2,), dtype=int64, numpy=array([4, 5])>, <tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 1])>, <tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.])>)
(<tf.Tensor: shape=(2,), dtype=int64, numpy=array([6, 7])>, <tf.Tensor: shape=(2,), dtype=int64, numpy=array([16, 17])>, <tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.])>)
(<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 1])>, <tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 1])>, <tf.Tensor: shape=(1,), dtype=float64, numpy=array([1.])>)
(<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 3])>, <tf.Tensor: shape=(2,), dtype=int64, numpy=array([10, 11])>, <tf.Tensor: shape=(1,), dtype=float64, numpy=array([0.])>)
(<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 3])>, <tf.Tensor: shape=(2,), dtype=int64, numpy=a

In [17]:
dy0

<TensorSliceDataset shapes: (1,), types: tf.float64>

In [18]:
tf.stack([dy0, dy1])

ValueError: Attempt to convert a value (<TensorSliceDataset shapes: (1,), types: tf.float64>) with an unsupported type (<class 'tensorflow.python.data.ops.dataset_ops.TensorSliceDataset'>) to a Tensor.