In [1]:
import numpy as np
import tensorflow as tf

In [15]:
x = np.arange(20).reshape(10, -1)

In [16]:
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [88]:
theta = np.arange(20).reshape(10, -1)

In [79]:
y0 = np.zeros(x.shape[0]).reshape(10, -1)
y1 = np.ones(x.shape[0]).reshape(10, -1)

In [80]:
dy0 = tf.data.Dataset.from_tensor_slices(y0)
dy1 = tf.data.Dataset.from_tensor_slices(y1)

In [89]:
dx = tf.data.Dataset.from_tensor_slices(x)
dtheta = tf.data.Dataset.from_tensor_slices(theta)

In [90]:
for d in dx.shuffle(buffer_size=10):
    print(d)

tf.Tensor([10 11], shape=(2,), dtype=int64)
tf.Tensor([16 17], shape=(2,), dtype=int64)
tf.Tensor([18 19], shape=(2,), dtype=int64)
tf.Tensor([14 15], shape=(2,), dtype=int64)
tf.Tensor([4 5], shape=(2,), dtype=int64)
tf.Tensor([0 1], shape=(2,), dtype=int64)
tf.Tensor([2 3], shape=(2,), dtype=int64)
tf.Tensor([12 13], shape=(2,), dtype=int64)
tf.Tensor([8 9], shape=(2,), dtype=int64)
tf.Tensor([6 7], shape=(2,), dtype=int64)


In [91]:
for d in dx.batch(3):
    print(d)

tf.Tensor(
[[0 1]
 [2 3]
 [4 5]], shape=(3, 2), dtype=int64)
tf.Tensor(
[[ 6  7]
 [ 8  9]
 [10 11]], shape=(3, 2), dtype=int64)
tf.Tensor(
[[12 13]
 [14 15]
 [16 17]], shape=(3, 2), dtype=int64)
tf.Tensor([[18 19]], shape=(1, 2), dtype=int64)


In [93]:
for d in tf.data.Dataset.zip((dx, dtheta.shuffle(10))).shuffle(10):
    print(d)

(<tf.Tensor: id=1366, shape=(2,), dtype=int64, numpy=array([16, 17])>, <tf.Tensor: id=1367, shape=(2,), dtype=int64, numpy=array([18, 19])>)
(<tf.Tensor: id=1368, shape=(2,), dtype=int64, numpy=array([12, 13])>, <tf.Tensor: id=1369, shape=(2,), dtype=int64, numpy=array([16, 17])>)
(<tf.Tensor: id=1370, shape=(2,), dtype=int64, numpy=array([10, 11])>, <tf.Tensor: id=1371, shape=(2,), dtype=int64, numpy=array([8, 9])>)
(<tf.Tensor: id=1372, shape=(2,), dtype=int64, numpy=array([0, 1])>, <tf.Tensor: id=1373, shape=(2,), dtype=int64, numpy=array([2, 3])>)
(<tf.Tensor: id=1374, shape=(2,), dtype=int64, numpy=array([6, 7])>, <tf.Tensor: id=1375, shape=(2,), dtype=int64, numpy=array([6, 7])>)
(<tf.Tensor: id=1376, shape=(2,), dtype=int64, numpy=array([14, 15])>, <tf.Tensor: id=1377, shape=(2,), dtype=int64, numpy=array([4, 5])>)
(<tf.Tensor: id=1378, shape=(2,), dtype=int64, numpy=array([2, 3])>, <tf.Tensor: id=1379, shape=(2,), dtype=int64, numpy=array([0, 1])>)
(<tf.Tensor: id=1380, shape=(

In [169]:
X = tf.data.Dataset.concatenate(dx, dx)
T = tf.data.Dataset.concatenate(dtheta, dtheta.shuffle(10))
Y = tf.data.Dataset.concatenate(dy1, dy0)

In [170]:
bigD = tf.data.Dataset.zip((X, T, Y))

In [159]:
for x, t, y in bigD.shuffle(20):
    print(x.numpy(), t.numpy(), y.numpy())

[0 1] [14 15] [0.]
[10 11] [8 9] [0.]
[6 7] [0 1] [0.]
[2 3] [2 3] [1.]
[14 15] [18 19] [0.]
[6 7] [6 7] [1.]
[0 1] [0 1] [1.]
[4 5] [6 7] [0.]
[12 13] [10 11] [0.]
[18 19] [2 3] [0.]
[10 11] [10 11] [1.]
[8 9] [8 9] [1.]
[14 15] [14 15] [1.]
[8 9] [4 5] [0.]
[16 17] [16 17] [1.]
[12 13] [12 13] [1.]
[4 5] [4 5] [1.]
[18 19] [18 19] [1.]
[2 3] [16 17] [0.]
[16 17] [12 13] [0.]


In [171]:
s = bigD.shuffle(20)

In [180]:
s

<ShuffleDataset shapes: ((2,), (2,), (1,)), types: (tf.int64, tf.int64, tf.float64)>

In [175]:
for e in s:
    print(e)

(<tf.Tensor: id=5880, shape=(2,), dtype=int64, numpy=array([4, 5])>, <tf.Tensor: id=5881, shape=(2,), dtype=int64, numpy=array([8, 9])>, <tf.Tensor: id=5882, shape=(1,), dtype=float64, numpy=array([0.])>)
(<tf.Tensor: id=5883, shape=(2,), dtype=int64, numpy=array([12, 13])>, <tf.Tensor: id=5884, shape=(2,), dtype=int64, numpy=array([18, 19])>, <tf.Tensor: id=5885, shape=(1,), dtype=float64, numpy=array([0.])>)
(<tf.Tensor: id=5886, shape=(2,), dtype=int64, numpy=array([8, 9])>, <tf.Tensor: id=5887, shape=(2,), dtype=int64, numpy=array([8, 9])>, <tf.Tensor: id=5888, shape=(1,), dtype=float64, numpy=array([1.])>)
(<tf.Tensor: id=5889, shape=(2,), dtype=int64, numpy=array([8, 9])>, <tf.Tensor: id=5890, shape=(2,), dtype=int64, numpy=array([2, 3])>, <tf.Tensor: id=5891, shape=(1,), dtype=float64, numpy=array([0.])>)
(<tf.Tensor: id=5892, shape=(2,), dtype=int64, numpy=array([14, 15])>, <tf.Tensor: id=5893, shape=(2,), dtype=int64, numpy=array([6, 7])>, <tf.Tensor: id=5894, shape=(1,), dtyp

In [176]:
dy0

<TensorSliceDataset shapes: (1,), types: tf.float64>

In [177]:
tf.stack([dy0, dy1])

ValueError: Attempt to convert a value (<TensorSliceDataset shapes: (1,), types: tf.float64>) with an unsupported type (<class 'tensorflow.python.data.ops.dataset_ops.TensorSliceDataset'>) to a Tensor.